############# English navigation ##############

# main menu
[[main]]
name = "Главная"
url = "/"
weight = 1

[[main]]
name = "Сведения об образовательной организации"
url = "/education"
weight = 2

# footer menu
[[footer]]
name = "Политика конфиденциальности"
url = "/privacy-policy"
weight = 1
